### ISSUE TITLE
Broken dependencies in `conda-environment.yml`

### ISSUE THREAD

**Issue by dmraji** [CMAP-REPOS/cmap_trip-based_model#3]
The `.yml` providing an environment configuration attempts to install package versions that are incompatible; some examples:

numba v0.53 doesn't work with tbb v2021.4
numba v0.53 doesn't work with numpy v1.21

**Comment by nrferguson** [comment]
According to package metadata, the examples provided are not true of numba 0.53.0. This is the version that is installed after conda solves the environment. Where are you experiencing broken dependencies?

numba 0.53.0 py39hf11a4ad_0
---------------------------
file name   : numba-0.53.0-py39hf11a4ad_0.conda
name        : numba
version     : 0.53.0
build       : py39hf11a4ad_0
build number: 0
size        : 3.3 MB
license     : BSD-2-Clause
subdir      : win-64
url         : https://repo.anaconda.com/pkgs/main/win-64/numba-0.53.0-py39hf11a4ad_0.conda
md5         : 2e77051ca04b5328ddcd9bc0ffb94f13
timestamp   : 2021-03-16 10:11:24 UTC
constraints :
  - libopenblas !=0.3.6
  - scipy >=1.0
  - cudatoolkit >=9.0
dependencies:
  - llvmlite >=0.36.0,<0.37.0a0
  - numpy >=1.16.6,<2.0a0
  - python >=3.9,<3.10.0a0
  - setuptools
  - vc >=14.1,<15.0a0
  - vs2015_runtime >=14.16.27012,<15.0a0

**Comment by dmraji** [comment]
Hi Nick -- thanks for writing back. I am getting the following with a clean repo setup:


```
Could not solve for environment specs
The following packages are incompatible
├─ numba 0.53**  is installable and it requires
│  └─ tbb >=2019.5,<=2020.3 , which can be installed;
└─ tbb 2021.4**  is uninstallable because it conflicts with any installable versions previously reported.
```

Then, if I remove the `tbb` packages from the spec:

```
Could not solve for environment specs
The following packages are incompatible
├─ numba 0.53**  is installable with the potential options
│  ├─ numba 0.53.0 would require
│  │  └─ numpy >=1.16.6,<1.21.0a0 , which can be installed;
│  ├─ numba [0.53.0|0.53.1] would require
│  │  └─ numpy >=1.19.5,<1.21.0a0 , which can be installed;
│  └─ numba 0.53.1 would require
│     └─ numpy >=1.17.5,<1.21.0a0 , which can be installed;
└─ numpy 1.21**  is uninstallable because it conflicts with any installable versions previously reported.
```

Please let me know if I am doing something wrong here.

Thanks,
David

**Comment by nrferguson** [comment]
It appears the solver is listing the `tbb` dependency for `numba 0.53.1`, and the upper limit on the `numpy` dependency leads me to believe the solver is outdated. There are no conflicts when using `conda 23.11.0`, which creates the environment successfully with `numba 0.53.0`, `tbb 2021.4.0`, and `numpy 1.21.6`.

**Comment by dmraji** [comment]
You're exactly right, this was the issue! Thank you for the assistance, apologies for the trouble.
